version: "3.7"

volumes:
  postgres_data:

services:
  postgres:
    container_name: django-starter-postgres
    image: postgres
    restart: always
    
    env_file:
      - .env
  django-project:
    container_name: giftprojects
    depends_on:
      - postgres
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./giftprojects/:/giftprojects/
      - ./giftapp/:/giftapp/
      - ./img/:/img/
    env_file:
      - .env
  nginx:
    container_name: gitftprojects-nginx
    image: nginx:1.19.0-alpine
    ports:
      - "8000:80"
    volumes:
      - ./static:/code/static
      - ./media:/code/media
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - django-project
    restart: always