# Generated by Django 4.0 on 2022-12-13 20:27

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('giftapp', '0020_alter_product_price_currency_alter_wishlist_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=models.CharField(choices=[('ISK', 'ISK'), ('GEK', 'GEK'), ('ETB', 'ETB'), ('ZWR', 'ZWR'), ('JOD', 'JOD'), ('DKK', 'DKK'), ('MCF', 'MCF'), ('MUR', 'MUR'), ('UYU', 'UYU'), ('EEK', 'EEK'), ('NIC', 'NIC'), ('KYD', 'KYD'), ('BOB', 'BOB'), ('GEL', 'GEL'), ('BRZ', 'BRZ'), ('BIF', 'BIF'), ('RUR', 'RUR'), ('LRD', 'LRD'), ('THB', 'THB'), ('MDC', 'MDC'), ('YUR', 'YUR'), ('RSD', 'RSD'), ('CSD', 'CSD'), ('VED', 'VED'), ('GBP', 'GBP'), ('ILP', 'ILP'), ('CNH', 'CNH'), ('XFO', 'XFO'), ('GYD', 'GYD'), ('YUD', 'YUD'), ('YUN', 'YUN'), ('CYP', 'CYP'), ('DJF', 'DJF'), ('FKP', 'FKP'), ('ANG', 'ANG'), ('GTQ', 'GTQ'), ('DZD', 'DZD'), ('INR', 'INR'), ('SRD', 'SRD'), ('BOP', 'BOP'), ('XRE', 'XRE'), ('AFA', 'AFA'), ('MMK', 'MMK'), ('PGK', 'PGK'), ('TWD', 'TWD'), ('KWD', 'KWD'), ('KGS', 'KGS'), ('NPR', 'NPR'), ('XBB', 'XBB'), ('BEL', 'BEL'), ('BRC', 'BRC'), ('ZMW', 'ZMW'), ('MZE', 'MZE'), ('DOP', 'DOP'), ('MGA', 'MGA'), ('UGX', 'UGX'), ('BRB', 'BRB'), ('MZM', 'MZM'), ('USN', 'USN'), ('ATS', 'ATS'), ('TRL', 'TRL'), ('XPT', 'XPT'), ('DEM', 'DEM'), ('TRY', 'TRY'), ('BYB', 'BYB'), ('XBC', 'XBC'), ('BHD', 'BHD'), ('CHE', 'CHE'), ('AED', 'AED'), ('ZMK', 'ZMK'), ('MGF', 'MGF'), ('XAG', 'XAG'), ('MXN', 'MXN'), ('SVC', 'SVC'), ('VUV', 'VUV'), ('SDP', 'SDP'), ('LBP', 'LBP'), ('BWP', 'BWP'), ('JMD', 'JMD'), ('ARL', 'ARL'), ('PAB', 'PAB'), ('ZRN', 'ZRN'), ('SOS', 'SOS'), ('ALL', 'ALL'), ('ARA', 'ARA'), ('STN', 'STN'), ('KHR', 'KHR'), ('AFN', 'AFN'), ('CLF', 'CLF'), ('AOR', 'AOR'), ('PTE', 'PTE'), ('XAF', 'XAF'), ('MXV', 'MXV'), ('COP', 'COP'), ('TMT', 'TMT'), ('OMR', 'OMR'), ('MTL', 'MTL'), ('LTL', 'LTL'), ('GHS', 'GHS'), ('KRH', 'KRH'), ('SZL', 'SZL'), ('BSD', 'BSD'), ('EUR', 'EUR'), ('UGS', 'UGS'), ('MAF', 'MAF'), ('BGO', 'BGO'), ('ZAL', 'ZAL'), ('BYR', 'BYR'), ('VEB', 'VEB'), ('ZWD', 'ZWD'), ('RHD', 'RHD'), ('BZD', 'BZD'), ('PLN', 'PLN'), ('BAM', 'BAM'), ('RON', 'RON'), ('KRO', 'KRO'), ('ZAR', 'ZAR'), ('UAH', 'UAH'), ('ADP', 'ADP'), ('TJS', 'TJS'), ('ZRZ', 'ZRZ'), ('ECS', 'ECS'), ('PKR', 'PKR'), ('BUK', 'BUK'), ('CUP', 'CUP'), ('KZT', 'KZT'), ('LKR', 'LKR'), ('NIO', 'NIO'), ('NAD', 'NAD'), ('UYI', 'UYI'), ('YER', 'YER'), ('ERN', 'ERN'), ('USS', 'USS'), ('FIM', 'FIM'), ('IRR', 'IRR'), ('UAK', 'UAK'), ('BGN', 'BGN'), ('PES', 'PES'), ('TMM', 'TMM'), ('IQD', 'IQD'), ('SAR', 'SAR'), ('MWK', 'MWK'), ('AOK', 'AOK'), ('SHP', 'SHP'), ('BBD', 'BBD'), ('BRL', 'BRL'), ('TTD', 'TTD'), ('GNF', 'GNF'), ('PHP', 'PHP'), ('ROL', 'ROL'), ('SRG', 'SRG'), ('BND', 'BND'), ('SEK', 'SEK'), ('ILR', 'ILR'), ('KMF', 'KMF'), ('ARM', 'ARM'), ('BOL', 'BOL'), ('CNX', 'CNX'), ('PEN', 'PEN'), ('GNS', 'GNS'), ('TOP', 'TOP'), ('UYW', 'UYW'), ('HKD', 'HKD'), ('AMD', 'AMD'), ('MKD', 'MKD'), ('MKN', 'MKN'), ('TPE', 'TPE'), ('BOV', 'BOV'), ('LTT', 'LTT'), ('ECV', 'ECV'), ('HRD', 'HRD'), ('XXX', 'XXX'), ('XAU', 'XAU'), ('NLG', 'NLG'), ('CRC', 'CRC'), ('XTS', 'XTS'), ('MDL', 'MDL'), ('MRU', 'MRU'), ('AOA', 'AOA'), ('TZS', 'TZS'), ('YDD', 'YDD'), ('SIT', 'SIT'), ('ITL', 'ITL'), ('FJD', 'FJD'), ('LVL', 'LVL'), ('COU', 'COU'), ('XOF', 'XOF'), ('CNY', 'CNY'), ('TJR', 'TJR'), ('BYN', 'BYN'), ('AZM', 'AZM'), ('CAD', 'CAD'), ('LSL', 'LSL'), ('RUB', 'RUB'), ('AWG', 'AWG'), ('SKK', 'SKK'), ('VES', 'VES'), ('BEF', 'BEF'), ('XPF', 'XPF'), ('USD', 'USD'), ('BGL', 'BGL'), ('XBD', 'XBD'), ('GIP', 'GIP'), ('HTG', 'HTG'), ('BRR', 'BRR'), ('ALK', 'ALK'), ('BEC', 'BEC'), ('HUF', 'HUF'), ('SDD', 'SDD'), ('MYR', 'MYR'), ('HRK', 'HRK'), ('LUL', 'LUL'), ('ESB', 'ESB'), ('MLF', 'MLF'), ('MAD', 'MAD'), ('VND', 'VND'), ('SCR', 'SCR'), ('BRN', 'BRN'), ('CZK', 'CZK'), ('XDR', 'XDR'), ('JPY', 'JPY'), ('CLP', 'CLP'), ('XBA', 'XBA'), ('PLZ', 'PLZ'), ('XPD', 'XPD'), ('ZWL', 'ZWL'), ('NGN', 'NGN'), ('SYP', 'SYP'), ('NZD', 'NZD'), ('BDT', 'BDT'), ('CVE', 'CVE'), ('ESA', 'ESA'), ('SSP', 'SSP'), ('XCD', 'XCD'), ('GWE', 'GWE'), ('GRD', 'GRD'), ('ARS', 'ARS'), ('KRW', 'KRW'), ('MZN', 'MZN'), ('RWF', 'RWF'), ('LUC', 'LUC'), ('MRO', 'MRO'), ('XSU', 'XSU'), ('DDM', 'DDM'), ('ILS', 'ILS'), ('HNL', 'HNL'), ('QAR', 'QAR'), ('STD', 'STD'), ('SUR', 'SUR'), ('AZN', 'AZN'), ('FRF', 'FRF'), ('IDR', 'IDR'), ('NOK', 'NOK'), ('IEP', 'IEP'), ('SBD', 'SBD'), ('GMD', 'GMD'), ('EGP', 'EGP'), ('BAD', 'BAD'), ('KES', 'KES'), ('BTN', 'BTN'), ('XUA', 'XUA'), ('BRE', 'BRE'), ('BGM', 'BGM'), ('GQE', 'GQE'), ('SDG', 'SDG'), ('MTP', 'MTP'), ('VNN', 'VNN'), ('GHC', 'GHC'), ('KPW', 'KPW'), ('GWP', 'GWP'), ('CDF', 'CDF'), ('XFU', 'XFU'), ('AON', 'AON'), ('PYG', 'PYG'), ('MXP', 'MXP'), ('TND', 'TND'), ('CHW', 'CHW'), ('SGD', 'SGD'), ('ARP', 'ARP'), ('AUD', 'AUD'), ('CHF', 'CHF'), ('UYP', 'UYP'), ('BAN', 'BAN'), ('SLL', 'SLL'), ('MOP', 'MOP'), ('PEI', 'PEI'), ('LUF', 'LUF'), ('YUM', 'YUM'), ('MVR', 'MVR'), ('XEU', 'XEU'), ('CUC', 'CUC'), ('SLE', 'SLE'), ('ISJ', 'ISJ'), ('UZS', 'UZS'), ('ESP', 'ESP'), ('WST', 'WST'), ('CLE', 'CLE'), ('MNT', 'MNT'), ('VEF', 'VEF'), ('BMD', 'BMD'), ('LYD', 'LYD'), ('LVR', 'LVR'), ('LAK', 'LAK'), ('MVP', 'MVP'), ('CSK', 'CSK')], default='USD', max_length=3),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wish',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wish',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='category', chained_model_field='name', to='giftapp.Product'),
        ),
    ]
