# Generated by Django 4.0 on 2022-12-13 20:31

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0022_alter_product_price_currency_alter_wishlist_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=models.CharField(choices=[('MKN', 'MKN'), ('DZD', 'DZD'), ('CHE', 'CHE'), ('SVC', 'SVC'), ('OMR', 'OMR'), ('KMF', 'KMF'), ('SDG', 'SDG'), ('BEC', 'BEC'), ('LRD', 'LRD'), ('SBD', 'SBD'), ('CRC', 'CRC'), ('FRF', 'FRF'), ('TMT', 'TMT'), ('LVR', 'LVR'), ('DKK', 'DKK'), ('CNH', 'CNH'), ('TJR', 'TJR'), ('FKP', 'FKP'), ('BRE', 'BRE'), ('TRL', 'TRL'), ('GRD', 'GRD'), ('CUC', 'CUC'), ('VES', 'VES'), ('SEK', 'SEK'), ('HRK', 'HRK'), ('MRU', 'MRU'), ('BMD', 'BMD'), ('SOS', 'SOS'), ('XAG', 'XAG'), ('SIT', 'SIT'), ('XDR', 'XDR'), ('ARP', 'ARP'), ('TTD', 'TTD'), ('UYI', 'UYI'), ('VND', 'VND'), ('PYG', 'PYG'), ('MGA', 'MGA'), ('MZN', 'MZN'), ('BOV', 'BOV'), ('PEI', 'PEI'), ('EEK', 'EEK'), ('ITL', 'ITL'), ('CHW', 'CHW'), ('IRR', 'IRR'), ('NIO', 'NIO'), ('PGK', 'PGK'), ('LSL', 'LSL'), ('MVR', 'MVR'), ('ROL', 'ROL'), ('VNN', 'VNN'), ('MWK', 'MWK'), ('FIM', 'FIM'), ('MXN', 'MXN'), ('LAK', 'LAK'), ('KRO', 'KRO'), ('GNF', 'GNF'), ('SKK', 'SKK'), ('CUP', 'CUP'), ('MDC', 'MDC'), ('ERN', 'ERN'), ('XBA', 'XBA'), ('AED', 'AED'), ('ETB', 'ETB'), ('ATS', 'ATS'), ('LUF', 'LUF'), ('RUB', 'RUB'), ('TPE', 'TPE'), ('BRC', 'BRC'), ('CLF', 'CLF'), ('UYW', 'UYW'), ('XPF', 'XPF'), ('BWP', 'BWP'), ('UZS', 'UZS'), ('KYD', 'KYD'), ('AZN', 'AZN'), ('YUM', 'YUM'), ('BOP', 'BOP'), ('MXV', 'MXV'), ('CSD', 'CSD'), ('XEU', 'XEU'), ('QAR', 'QAR'), ('LUC', 'LUC'), ('SDP', 'SDP'), ('XBC', 'XBC'), ('ZMW', 'ZMW'), ('GWP', 'GWP'), ('AMD', 'AMD'), ('KZT', 'KZT'), ('RSD', 'RSD'), ('MUR', 'MUR'), ('USD', 'USD'), ('ESB', 'ESB'), ('MNT', 'MNT'), ('GHS', 'GHS'), ('USN', 'USN'), ('CNX', 'CNX'), ('JMD', 'JMD'), ('DOP', 'DOP'), ('BUK', 'BUK'), ('TND', 'TND'), ('EUR', 'EUR'), ('XBB', 'XBB'), ('AFA', 'AFA'), ('BGM', 'BGM'), ('XFO', 'XFO'), ('RHD', 'RHD'), ('LYD', 'LYD'), ('LTL', 'LTL'), ('DEM', 'DEM'), ('XAF', 'XAF'), ('KPW', 'KPW'), ('MGF', 'MGF'), ('ISK', 'ISK'), ('UYU', 'UYU'), ('SYP', 'SYP'), ('AOR', 'AOR'), ('MAF', 'MAF'), ('DDM', 'DDM'), ('DJF', 'DJF'), ('ZMK', 'ZMK'), ('CDF', 'CDF'), ('SDD', 'SDD'), ('MOP', 'MOP'), ('SLE', 'SLE'), ('NOK', 'NOK'), ('FJD', 'FJD'), ('GYD', 'GYD'), ('XFU', 'XFU'), ('BAM', 'BAM'), ('MXP', 'MXP'), ('YUD', 'YUD'), ('STN', 'STN'), ('YER', 'YER'), ('TWD', 'TWD'), ('BZD', 'BZD'), ('ZWL', 'ZWL'), ('UAH', 'UAH'), ('UYP', 'UYP'), ('CZK', 'CZK'), ('XPD', 'XPD'), ('IQD', 'IQD'), ('SCR', 'SCR'), ('MVP', 'MVP'), ('XOF', 'XOF'), ('BGN', 'BGN'), ('MAD', 'MAD'), ('PEN', 'PEN'), ('SGD', 'SGD'), ('INR', 'INR'), ('HKD', 'HKD'), ('USS', 'USS'), ('PLZ', 'PLZ'), ('ALK', 'ALK'), ('MTP', 'MTP'), ('ESP', 'ESP'), ('NLG', 'NLG'), ('STD', 'STD'), ('BBD', 'BBD'), ('BGO', 'BGO'), ('CHF', 'CHF'), ('CVE', 'CVE'), ('BSD', 'BSD'), ('LVL', 'LVL'), ('SUR', 'SUR'), ('ARM', 'ARM'), ('GIP', 'GIP'), ('BYR', 'BYR'), ('HNL', 'HNL'), ('AON', 'AON'), ('JOD', 'JOD'), ('BTN', 'BTN'), ('RUR', 'RUR'), ('MKD', 'MKD'), ('TJS', 'TJS'), ('GBP', 'GBP'), ('SHP', 'SHP'), ('GMD', 'GMD'), ('BHD', 'BHD'), ('WST', 'WST'), ('PTE', 'PTE'), ('HUF', 'HUF'), ('MZE', 'MZE'), ('BYB', 'BYB'), ('RWF', 'RWF'), ('AUD', 'AUD'), ('VEB', 'VEB'), ('XUA', 'XUA'), ('SAR', 'SAR'), ('XTS', 'XTS'), ('ESA', 'ESA'), ('BRZ', 'BRZ'), ('MTL', 'MTL'), ('GEL', 'GEL'), ('ZWD', 'ZWD'), ('JPY', 'JPY'), ('ZWR', 'ZWR'), ('IEP', 'IEP'), ('NPR', 'NPR'), ('BIF', 'BIF'), ('HTG', 'HTG'), ('CAD', 'CAD'), ('THB', 'THB'), ('MLF', 'MLF'), ('LBP', 'LBP'), ('ZRZ', 'ZRZ'), ('ARA', 'ARA'), ('BAN', 'BAN'), ('CNY', 'CNY'), ('AOA', 'AOA'), ('PHP', 'PHP'), ('TMM', 'TMM'), ('AOK', 'AOK'), ('NZD', 'NZD'), ('BOL', 'BOL'), ('PKR', 'PKR'), ('ILR', 'ILR'), ('GEK', 'GEK'), ('TOP', 'TOP'), ('BGL', 'BGL'), ('BRR', 'BRR'), ('EGP', 'EGP'), ('LUL', 'LUL'), ('COU', 'COU'), ('SRG', 'SRG'), ('BRN', 'BRN'), ('COP', 'COP'), ('SSP', 'SSP'), ('XAU', 'XAU'), ('KES', 'KES'), ('VEF', 'VEF'), ('KHR', 'KHR'), ('SRD', 'SRD'), ('KRH', 'KRH'), ('UGS', 'UGS'), ('CLE', 'CLE'), ('BRL', 'BRL'), ('GNS', 'GNS'), ('BOB', 'BOB'), ('BYN', 'BYN'), ('ZAR', 'ZAR'), ('ZRN', 'ZRN'), ('ARL', 'ARL'), ('MYR', 'MYR'), ('ILP', 'ILP'), ('MCF', 'MCF'), ('AZM', 'AZM'), ('BND', 'BND'), ('GWE', 'GWE'), ('BRB', 'BRB'), ('XSU', 'XSU'), ('GTQ', 'GTQ'), ('PES', 'PES'), ('UAK', 'UAK'), ('RON', 'RON'), ('ARS', 'ARS'), ('XCD', 'XCD'), ('YUR', 'YUR'), ('SZL', 'SZL'), ('ECS', 'ECS'), ('XPT', 'XPT'), ('ECV', 'ECV'), ('YUN', 'YUN'), ('TZS', 'TZS'), ('ANG', 'ANG'), ('TRY', 'TRY'), ('SLL', 'SLL'), ('LKR', 'LKR'), ('NAD', 'NAD'), ('KRW', 'KRW'), ('NIC', 'NIC'), ('VED', 'VED'), ('YDD', 'YDD'), ('XRE', 'XRE'), ('LTT', 'LTT'), ('ALL', 'ALL'), ('BDT', 'BDT'), ('AFN', 'AFN'), ('PAB', 'PAB'), ('XBD', 'XBD'), ('XXX', 'XXX'), ('BAD', 'BAD'), ('CYP', 'CYP'), ('ILS', 'ILS'), ('GHC', 'GHC'), ('MDL', 'MDL'), ('ADP', 'ADP'), ('HRD', 'HRD'), ('ISJ', 'ISJ'), ('PLN', 'PLN'), ('BEF', 'BEF'), ('NGN', 'NGN'), ('AWG', 'AWG'), ('CSK', 'CSK'), ('KGS', 'KGS'), ('UGX', 'UGX'), ('IDR', 'IDR'), ('MMK', 'MMK'), ('GQE', 'GQE'), ('MZM', 'MZM'), ('BEL', 'BEL'), ('VUV', 'VUV'), ('MRO', 'MRO'), ('CLP', 'CLP'), ('ZAL', 'ZAL'), ('KWD', 'KWD')], default='USD', max_length=3),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wish',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wish',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='name', default=5, on_delete=django.db.models.deletion.CASCADE, to='giftapp.product'),
            preserve_default=False,
        ),
    ]
