# Generated by Django 4.0 on 2022-12-16 12:31

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0053_alter_product_price_currency_alter_wishlist_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='category',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='giftapp.productcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=models.CharField(choices=[('KRO', 'KRO'), ('XCD', 'XCD'), ('BGM', 'BGM'), ('BUK', 'BUK'), ('SRD', 'SRD'), ('SIT', 'SIT'), ('KYD', 'KYD'), ('VUV', 'VUV'), ('XPD', 'XPD'), ('ARP', 'ARP'), ('MAF', 'MAF'), ('WST', 'WST'), ('ZWR', 'ZWR'), ('PYG', 'PYG'), ('MTP', 'MTP'), ('CNX', 'CNX'), ('XEU', 'XEU'), ('PLN', 'PLN'), ('GIP', 'GIP'), ('MZM', 'MZM'), ('CNY', 'CNY'), ('MXP', 'MXP'), ('CUP', 'CUP'), ('MLF', 'MLF'), ('PES', 'PES'), ('NOK', 'NOK'), ('AOK', 'AOK'), ('BEF', 'BEF'), ('ALL', 'ALL'), ('CRC', 'CRC'), ('AZN', 'AZN'), ('RWF', 'RWF'), ('BRE', 'BRE'), ('XUA', 'XUA'), ('MAD', 'MAD'), ('ARL', 'ARL'), ('ILS', 'ILS'), ('BRC', 'BRC'), ('KPW', 'KPW'), ('CHW', 'CHW'), ('CNH', 'CNH'), ('TWD', 'TWD'), ('MGF', 'MGF'), ('ISJ', 'ISJ'), ('JMD', 'JMD'), ('MVR', 'MVR'), ('BGL', 'BGL'), ('JOD', 'JOD'), ('LTT', 'LTT'), ('CLF', 'CLF'), ('GWE', 'GWE'), ('ARA', 'ARA'), ('MKN', 'MKN'), ('DZD', 'DZD'), ('GRD', 'GRD'), ('BSD', 'BSD'), ('BYB', 'BYB'), ('ATS', 'ATS'), ('AMD', 'AMD'), ('NGN', 'NGN'), ('DEM', 'DEM'), ('COU', 'COU'), ('LVL', 'LVL'), ('MXN', 'MXN'), ('PKR', 'PKR'), ('SKK', 'SKK'), ('VEB', 'VEB'), ('XSU', 'XSU'), ('GBP', 'GBP'), ('BHD', 'BHD'), ('ESP', 'ESP'), ('VNN', 'VNN'), ('KRW', 'KRW'), ('KHR', 'KHR'), ('GHC', 'GHC'), ('HTG', 'HTG'), ('SLE', 'SLE'), ('YDD', 'YDD'), ('CAD', 'CAD'), ('RON', 'RON'), ('NIC', 'NIC'), ('FKP', 'FKP'), ('IQD', 'IQD'), ('LAK', 'LAK'), ('XAU', 'XAU'), ('SOS', 'SOS'), ('BMD', 'BMD'), ('DJF', 'DJF'), ('ERN', 'ERN'), ('BWP', 'BWP'), ('NLG', 'NLG'), ('MCF', 'MCF'), ('RSD', 'RSD'), ('STD', 'STD'), ('SAR', 'SAR'), ('CLP', 'CLP'), ('IDR', 'IDR'), ('TRY', 'TRY'), ('ZAR', 'ZAR'), ('MMK', 'MMK'), ('SUR', 'SUR'), ('PTE', 'PTE'), ('GTQ', 'GTQ'), ('EEK', 'EEK'), ('XTS', 'XTS'), ('NPR', 'NPR'), ('XPT', 'XPT'), ('LSL', 'LSL'), ('SCR', 'SCR'), ('SDD', 'SDD'), ('ZMK', 'ZMK'), ('TJR', 'TJR'), ('ADP', 'ADP'), ('STN', 'STN'), ('DKK', 'DKK'), ('USS', 'USS'), ('NZD', 'NZD'), ('XBB', 'XBB'), ('CSK', 'CSK'), ('TND', 'TND'), ('VEF', 'VEF'), ('MUR', 'MUR'), ('UYI', 'UYI'), ('AWG', 'AWG'), ('LVR', 'LVR'), ('SGD', 'SGD'), ('BRZ', 'BRZ'), ('GYD', 'GYD'), ('BYN', 'BYN'), ('ILR', 'ILR'), ('XRE', 'XRE'), ('PEN', 'PEN'), ('BRB', 'BRB'), ('XOF', 'XOF'), ('ILP', 'ILP'), ('BGO', 'BGO'), ('PGK', 'PGK'), ('ECV', 'ECV'), ('YER', 'YER'), ('AZM', 'AZM'), ('ISK', 'ISK'), ('BIF', 'BIF'), ('YUR', 'YUR'), ('TMT', 'TMT'), ('BZD', 'BZD'), ('MOP', 'MOP'), ('SDP', 'SDP'), ('PEI', 'PEI'), ('LBP', 'LBP'), ('AOR', 'AOR'), ('SVC', 'SVC'), ('COP', 'COP'), ('HRK', 'HRK'), ('VES', 'VES'), ('BDT', 'BDT'), ('MXV', 'MXV'), ('EUR', 'EUR'), ('ECS', 'ECS'), ('KZT', 'KZT'), ('MGA', 'MGA'), ('USD', 'USD'), ('UYW', 'UYW'), ('TOP', 'TOP'), ('MRO', 'MRO'), ('GEL', 'GEL'), ('BOP', 'BOP'), ('BGN', 'BGN'), ('YUM', 'YUM'), ('FIM', 'FIM'), ('IRR', 'IRR'), ('BAD', 'BAD'), ('JPY', 'JPY'), ('XDR', 'XDR'), ('HNL', 'HNL'), ('BBD', 'BBD'), ('MDL', 'MDL'), ('XAF', 'XAF'), ('UYU', 'UYU'), ('LTL', 'LTL'), ('SDG', 'SDG'), ('BND', 'BND'), ('GNF', 'GNF'), ('HKD', 'HKD'), ('MVP', 'MVP'), ('BEL', 'BEL'), ('CVE', 'CVE'), ('MDC', 'MDC'), ('CHE', 'CHE'), ('MZE', 'MZE'), ('MNT', 'MNT'), ('INR', 'INR'), ('KGS', 'KGS'), ('SHP', 'SHP'), ('SYP', 'SYP'), ('UGX', 'UGX'), ('ARS', 'ARS'), ('BOV', 'BOV'), ('MKD', 'MKD'), ('YUD', 'YUD'), ('GEK', 'GEK'), ('TJS', 'TJS'), ('ROL', 'ROL'), ('XAG', 'XAG'), ('ANG', 'ANG'), ('GHS', 'GHS'), ('USN', 'USN'), ('GNS', 'GNS'), ('VND', 'VND'), ('AOA', 'AOA'), ('CYP', 'CYP'), ('MRU', 'MRU'), ('ARM', 'ARM'), ('YUN', 'YUN'), ('CHF', 'CHF'), ('ALK', 'ALK'), ('ETB', 'ETB'), ('LRD', 'LRD'), ('LUC', 'LUC'), ('XBA', 'XBA'), ('QAR', 'QAR'), ('THB', 'THB'), ('SZL', 'SZL'), ('ZAL', 'ZAL'), ('TRL', 'TRL'), ('TZS', 'TZS'), ('KWD', 'KWD'), ('PAB', 'PAB'), ('UAK', 'UAK'), ('DDM', 'DDM'), ('VED', 'VED'), ('RHD', 'RHD'), ('XXX', 'XXX'), ('XPF', 'XPF'), ('PHP', 'PHP'), ('MWK', 'MWK'), ('ESB', 'ESB'), ('RUB', 'RUB'), ('KES', 'KES'), ('HRD', 'HRD'), ('GMD', 'GMD'), ('MZN', 'MZN'), ('ZWD', 'ZWD'), ('AON', 'AON'), ('SRG', 'SRG'), ('ZRN', 'ZRN'), ('PLZ', 'PLZ'), ('UAH', 'UAH'), ('XFO', 'XFO'), ('NIO', 'NIO'), ('GWP', 'GWP'), ('LKR', 'LKR'), ('FRF', 'FRF'), ('CLE', 'CLE'), ('XFU', 'XFU'), ('CUC', 'CUC'), ('UYP', 'UYP'), ('AUD', 'AUD'), ('ESA', 'ESA'), ('SEK', 'SEK'), ('FJD', 'FJD'), ('AFA', 'AFA'), ('HUF', 'HUF'), ('BRN', 'BRN'), ('AFN', 'AFN'), ('CDF', 'CDF'), ('LYD', 'LYD'), ('SSP', 'SSP'), ('BAM', 'BAM'), ('KMF', 'KMF'), ('SLL', 'SLL'), ('ITL', 'ITL'), ('RUR', 'RUR'), ('BRR', 'BRR'), ('UZS', 'UZS'), ('OMR', 'OMR'), ('SBD', 'SBD'), ('XBC', 'XBC'), ('ZMW', 'ZMW'), ('ZRZ', 'ZRZ'), ('EGP', 'EGP'), ('KRH', 'KRH'), ('BTN', 'BTN'), ('LUL', 'LUL'), ('BEC', 'BEC'), ('LUF', 'LUF'), ('XBD', 'XBD'), ('TPE', 'TPE'), ('BYR', 'BYR'), ('CZK', 'CZK'), ('TMM', 'TMM'), ('CSD', 'CSD'), ('BAN', 'BAN'), ('IEP', 'IEP'), ('NAD', 'NAD'), ('TTD', 'TTD'), ('MYR', 'MYR'), ('MTL', 'MTL'), ('UGS', 'UGS'), ('BRL', 'BRL'), ('BOB', 'BOB'), ('BOL', 'BOL'), ('ZWL', 'ZWL'), ('DOP', 'DOP'), ('AED', 'AED'), ('GQE', 'GQE')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wish',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='product_category', on_delete=django.db.models.deletion.CASCADE, to='giftapp.product'),
        ),
    ]
