# Generated by Django 4.0 on 2022-12-16 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0058_alter_product_price_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wish',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_id',
            field=models.ForeignKey(default=10000, on_delete=django.db.models.deletion.CASCADE, to='giftapp.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=models.CharField(choices=[('CHW', 'CHW'), ('BRE', 'BRE'), ('YUD', 'YUD'), ('BGM', 'BGM'), ('XXX', 'XXX'), ('YUM', 'YUM'), ('XPT', 'XPT'), ('KGS', 'KGS'), ('ZWR', 'ZWR'), ('CHE', 'CHE'), ('GYD', 'GYD'), ('LRD', 'LRD'), ('PGK', 'PGK'), ('ARS', 'ARS'), ('ISJ', 'ISJ'), ('BRR', 'BRR'), ('IRR', 'IRR'), ('XBB', 'XBB'), ('AZN', 'AZN'), ('MZM', 'MZM'), ('EGP', 'EGP'), ('AMD', 'AMD'), ('LBP', 'LBP'), ('NIC', 'NIC'), ('AFA', 'AFA'), ('ESP', 'ESP'), ('MGF', 'MGF'), ('PKR', 'PKR'), ('BOB', 'BOB'), ('DJF', 'DJF'), ('BRB', 'BRB'), ('SRD', 'SRD'), ('THB', 'THB'), ('LVL', 'LVL'), ('STN', 'STN'), ('NZD', 'NZD'), ('CLF', 'CLF'), ('GNS', 'GNS'), ('DDM', 'DDM'), ('OMR', 'OMR'), ('XDR', 'XDR'), ('ARP', 'ARP'), ('NAD', 'NAD'), ('MUR', 'MUR'), ('TRY', 'TRY'), ('MLF', 'MLF'), ('SRG', 'SRG'), ('MRU', 'MRU'), ('PEI', 'PEI'), ('SBD', 'SBD'), ('GWE', 'GWE'), ('PEN', 'PEN'), ('ETB', 'ETB'), ('IEP', 'IEP'), ('LTT', 'LTT'), ('BEC', 'BEC'), ('SSP', 'SSP'), ('PHP', 'PHP'), ('BDT', 'BDT'), ('AON', 'AON'), ('CNY', 'CNY'), ('AOR', 'AOR'), ('SEK', 'SEK'), ('XPD', 'XPD'), ('SVC', 'SVC'), ('MVR', 'MVR'), ('TJR', 'TJR'), ('KRW', 'KRW'), ('CNH', 'CNH'), ('BRL', 'BRL'), ('MMK', 'MMK'), ('BGN', 'BGN'), ('ALL', 'ALL'), ('CLE', 'CLE'), ('PLN', 'PLN'), ('SCR', 'SCR'), ('XPF', 'XPF'), ('BOP', 'BOP'), ('XBC', 'XBC'), ('RUR', 'RUR'), ('NLG', 'NLG'), ('TPE', 'TPE'), ('ARL', 'ARL'), ('SLL', 'SLL'), ('MKN', 'MKN'), ('XOF', 'XOF'), ('GRD', 'GRD'), ('RON', 'RON'), ('VEB', 'VEB'), ('BZD', 'BZD'), ('ARA', 'ARA'), ('KPW', 'KPW'), ('SLE', 'SLE'), ('ILS', 'ILS'), ('BOL', 'BOL'), ('DKK', 'DKK'), ('CUP', 'CUP'), ('UYP', 'UYP'), ('MRO', 'MRO'), ('UYW', 'UYW'), ('SHP', 'SHP'), ('UYI', 'UYI'), ('AOK', 'AOK'), ('ESB', 'ESB'), ('ILP', 'ILP'), ('TTD', 'TTD'), ('NIO', 'NIO'), ('MAF', 'MAF'), ('MZE', 'MZE'), ('BIF', 'BIF'), ('CDF', 'CDF'), ('HUF', 'HUF'), ('MKD', 'MKD'), ('KZT', 'KZT'), ('NOK', 'NOK'), ('DZD', 'DZD'), ('YUR', 'YUR'), ('RWF', 'RWF'), ('NPR', 'NPR'), ('MTP', 'MTP'), ('AED', 'AED'), ('ZMK', 'ZMK'), ('ZMW', 'ZMW'), ('MGA', 'MGA'), ('GTQ', 'GTQ'), ('PLZ', 'PLZ'), ('KMF', 'KMF'), ('LUC', 'LUC'), ('CRC', 'CRC'), ('USN', 'USN'), ('HNL', 'HNL'), ('KRO', 'KRO'), ('IQD', 'IQD'), ('CAD', 'CAD'), ('UAH', 'UAH'), ('BYB', 'BYB'), ('ITL', 'ITL'), ('UYU', 'UYU'), ('YER', 'YER'), ('SKK', 'SKK'), ('BEF', 'BEF'), ('ATS', 'ATS'), ('ARM', 'ARM'), ('BTN', 'BTN'), ('ECV', 'ECV'), ('MZN', 'MZN'), ('XAG', 'XAG'), ('JOD', 'JOD'), ('TOP', 'TOP'), ('VED', 'VED'), ('AZM', 'AZM'), ('KRH', 'KRH'), ('BRZ', 'BRZ'), ('LVR', 'LVR'), ('PYG', 'PYG'), ('MXN', 'MXN'), ('BBD', 'BBD'), ('ALK', 'ALK'), ('ESA', 'ESA'), ('HTG', 'HTG'), ('MXP', 'MXP'), ('KYD', 'KYD'), ('SYP', 'SYP'), ('CSK', 'CSK'), ('BAD', 'BAD'), ('INR', 'INR'), ('AUD', 'AUD'), ('WST', 'WST'), ('BAM', 'BAM'), ('BMD', 'BMD'), ('CHF', 'CHF'), ('TJS', 'TJS'), ('BAN', 'BAN'), ('CUC', 'CUC'), ('BYN', 'BYN'), ('EEK', 'EEK'), ('BGO', 'BGO'), ('SUR', 'SUR'), ('CLP', 'CLP'), ('MTL', 'MTL'), ('VES', 'VES'), ('BGL', 'BGL'), ('TND', 'TND'), ('VEF', 'VEF'), ('STD', 'STD'), ('BSD', 'BSD'), ('SDG', 'SDG'), ('SDD', 'SDD'), ('XCD', 'XCD'), ('ROL', 'ROL'), ('IDR', 'IDR'), ('HRK', 'HRK'), ('CSD', 'CSD'), ('MXV', 'MXV'), ('ZWD', 'ZWD'), ('MCF', 'MCF'), ('ZRZ', 'ZRZ'), ('MOP', 'MOP'), ('MWK', 'MWK'), ('XFU', 'XFU'), ('UZS', 'UZS'), ('ERN', 'ERN'), ('SIT', 'SIT'), ('NGN', 'NGN'), ('XSU', 'XSU'), ('CYP', 'CYP'), ('RHD', 'RHD'), ('LUF', 'LUF'), ('MDC', 'MDC'), ('UAK', 'UAK'), ('GNF', 'GNF'), ('HRD', 'HRD'), ('XAU', 'XAU'), ('AFN', 'AFN'), ('XAF', 'XAF'), ('ZAL', 'ZAL'), ('EUR', 'EUR'), ('ECS', 'ECS'), ('FIM', 'FIM'), ('BOV', 'BOV'), ('UGS', 'UGS'), ('CZK', 'CZK'), ('FKP', 'FKP'), ('BRC', 'BRC'), ('CVE', 'CVE'), ('AWG', 'AWG'), ('ADP', 'ADP'), ('XBD', 'XBD'), ('LKR', 'LKR'), ('COU', 'COU'), ('ZAR', 'ZAR'), ('QAR', 'QAR'), ('BYR', 'BYR'), ('BWP', 'BWP'), ('KES', 'KES'), ('VUV', 'VUV'), ('GMD', 'GMD'), ('GIP', 'GIP'), ('LAK', 'LAK'), ('BEL', 'BEL'), ('LSL', 'LSL'), ('MNT', 'MNT'), ('LUL', 'LUL'), ('XEU', 'XEU'), ('XRE', 'XRE'), ('RSD', 'RSD'), ('HKD', 'HKD'), ('XBA', 'XBA'), ('ISK', 'ISK'), ('SOS', 'SOS'), ('YUN', 'YUN'), ('ZRN', 'ZRN'), ('ANG', 'ANG'), ('LTL', 'LTL'), ('DEM', 'DEM'), ('SZL', 'SZL'), ('TMT', 'TMT'), ('BUK', 'BUK'), ('RUB', 'RUB'), ('XUA', 'XUA'), ('MYR', 'MYR'), ('MVP', 'MVP'), ('PES', 'PES'), ('XTS', 'XTS'), ('BRN', 'BRN'), ('TRL', 'TRL'), ('TWD', 'TWD'), ('GQE', 'GQE'), ('MDL', 'MDL'), ('TZS', 'TZS'), ('PAB', 'PAB'), ('ZWL', 'ZWL'), ('AOA', 'AOA'), ('GEK', 'GEK'), ('FRF', 'FRF'), ('GEL', 'GEL'), ('JPY', 'JPY'), ('VNN', 'VNN'), ('CNX', 'CNX'), ('SDP', 'SDP'), ('TMM', 'TMM'), ('PTE', 'PTE'), ('JMD', 'JMD'), ('KHR', 'KHR'), ('VND', 'VND'), ('BHD', 'BHD'), ('DOP', 'DOP'), ('GBP', 'GBP'), ('SGD', 'SGD'), ('SAR', 'SAR'), ('GWP', 'GWP'), ('USS', 'USS'), ('GHC', 'GHC'), ('YDD', 'YDD'), ('COP', 'COP'), ('ILR', 'ILR'), ('USD', 'USD'), ('XFO', 'XFO'), ('LYD', 'LYD'), ('GHS', 'GHS'), ('KWD', 'KWD'), ('UGX', 'UGX'), ('BND', 'BND'), ('MAD', 'MAD'), ('FJD', 'FJD')], default='USD', max_length=3),
        ),
    ]
